import { TCard } from '../types/card';
export const defaultCardList: TCard[]= [
    {
      id:1,
      suit: 'spades',
      value: 1,
      color: 'black',
    },
    {
      id:2,
      suit: 'spades',
      value: 2,
      color: 'black',
    },
    {
      id:3,
      suit: 'spades',
      value: 3,
      color: 'black',
    },
    {
      id:4,
      suit: 'spades',
      value: 4,
      color: 'black',
    },
    {
      id:5,
      suit: 'spades',
      value: 5,
      color: 'black',
    },
    {
      id:6,
      suit: 'spades',
      value: 6,
      color: 'black',
    },
    {
      id:7,
      suit: 'spades',
      value: 7,
      color: 'black',
    },
    {
      id:8,
      suit: 'spades',
      value: 8,
      color: 'black',
    },
    {
      id:9,
      suit: 'spades',
      value: 9,
      color: 'black',
    },
    {
      id:10,
      suit: 'spades',
      value: 10,
      color: 'black',
    },
    {
      id:11,
      suit: 'spades',
      value: 11,
      color: 'black',
    },
    {
      id:12,
      suit: 'spades',
      value: 12,
      color: 'black',
    },
    {
      id:13,
      suit: 'spades',
      value: 13,
      color: 'black',
    },
    {
      id:14,
      suit: 'hearts',
      value: 1,
      color: 'red',
    },
    {
      id:15,
      suit: 'hearts',
      value: 2,
      color: 'red',
    },
    {
      id:16,
      suit: 'hearts',
      value: 3,
      color: 'red',
    },
    {
      id:17,
      suit: 'hearts',
      value: 4,
      color: 'red',
    },
    {
      id:18,
      suit: 'hearts',
      value: 5,
      color: 'red',
    },
    {
      id:19,
      suit: 'hearts',
      value: 6,
      color: 'red',
    },
    {
      id:20,
      suit: 'hearts',
      value: 7,
      color: 'red',
    },
    {
      id:21,
      suit: 'hearts',
      value: 8,
      color: 'red',
    },
    {
      id:22,
      suit: 'hearts',
      value: 9,
      color: 'red',
    },
    {
      id:23,
      suit: 'hearts',
      value: 10,
      color: 'red',
    },
    {
      id:24,
      suit: 'hearts',
      value: 11,
      color: 'red',
    },
    {
      id:25,
      suit: 'hearts',
      value: 12,
      color: 'red',
    },
    {
      id:26,
      suit: 'hearts',
      value: 13,
      color: 'red',
    },
    {
      id:27,
      suit: 'clubs',
      value: 1,
      color: 'black',
    },
    {
      id:28,
      suit: 'clubs',
      value: 2,
      color: 'black',
    },
    {
      id:29,
      suit: 'clubs',
      value: 3,
      color: 'black',
    },
    {
      id:30,
      suit: 'clubs',
      value: 4,
      color: 'black',
    },
    {
      id:31,
      suit: 'clubs',
      value: 5,
      color: 'black',
    },
    {
      id:32,
      suit: 'clubs',
      value: 6,
      color: 'black',
    },
    {
      id:33,
      suit: 'clubs',
      value: 7,
      color: 'black',
    },
    {
      id:34,
      suit: 'clubs',
      value: 8,
      color: 'black',
    },
    {
      id:35,
      suit: 'clubs',
      value: 9,
      color: 'black',
    },
    {
      id:36,
      suit: 'clubs',
      value: 10,
      color: 'black',
    },
    {
      id:37,
      suit: 'clubs',
      value: 11,
      color: 'black',
    },
    {
      id:38,
      suit: 'clubs',
      value: 12,
      color: 'black',
    },
    {
      id:39,
      suit: 'clubs',
      value: 13,
      color: 'black',
    },
    {
      id:40,
      suit: 'diamonds',
      value: 1,
      color: 'red',
    },
    {
      id:41,
      suit: 'diamonds',
      value: 2,
      color: 'red',
    },
    {
      id:42,
      suit: 'diamonds',
      value: 3,
      color: 'red',
    },
    {
      id:43,
      suit: 'diamonds',
      value: 4,
      color: 'red',
    },
    {
      id:44,
      suit: 'diamonds',
      value: 5,
      color: 'red',
    },
    {
      id:45,
      suit: 'diamonds',
      value: 6,
      color: 'red',
    },
    {
      id:46,
      suit: 'diamonds',
      value: 7,
      color: 'red',
    },
    {
      id:47,
      suit: 'diamonds',
      value: 8,
      color: 'red',
    },
    {
      id:48,
      suit: 'diamonds',
      value: 9,
      color: 'red',
    },
    {
      id:49,
      suit: 'diamonds',
      value: 10,
      color: 'red',
    },
    {
      id:50,
      suit: 'diamonds',
      value: 11,
      color: 'red',
    },
    {
      id:51,
      suit: 'diamonds',
      value: 12,
      color: 'red',
    }, {
      id:52,
      suit: 'diamonds',
      value: 13,
      color: 'red',
    },
  ];